roles:
  "auth:anon":
    priority: 0
    permissions:
      - "credentials:get"
      - "credentials:exist"
      - "credentials:create"
      - "credentials:email:patch"
      - "credentials:password:reset"
      - "shortCode:password:reset"
      - "shortCode:register"
  "auth:user":
    priority: 1
    inherits:
      - "auth:anon"
    permissions:
      - "credentials:password:patch"
      - "shortCode:email:update"
  "auth:admin":
    priority: 2
    inherits:
      - "auth:user"
    permissions:
      - "credentials:list"
  "auth:superadmin":
    priority: 3
    inherits:
      - "auth:admin"
    permissions:
      - "credentials:role:patch"
